export { default as Signin } from './signin'
export { default as Home } from './home'
export { default as Signup } from './signup'
export { default as Browse } from './browse'
export { default as Student } from './student'
export { default as Result } from './result'
export { default as Registration } from './registration'
export { default as Courses } from './courses'